FROM python:3.11.9-slim

# Copy requirements file
COPY requirements_docker_streamlit.txt .

# Update pip
RUN pip --timeout=30000 install --no-cache-dir --upgrade pip

# Install dependecies
RUN pip --timeout=30000 install --no-cache-dir -r requirements_docker_streamlit.txt

# Copy API
RUN mkdir /streamlit/
COPY ./streamlit /streamlit

# Set workdir
WORKDIR /

# Expose app port
EXPOSE 8501

# Start application
CMD ["streamlit", "run", "streamlit/predict.py", "0.0.0.0", "--port", "8501"]